public with sharing class contactrollupsummary implements Database.Batchable<SObject>
{
            public Database.queryLocator  start(Database.BatchableContext bc)
            {
                        return null;
            }

            public  void execute(Database.BatchableContext bc , List<SObject> scope)
            {
                        
            }

            public void finish(Database.BatchableContext bc)
            {

            }
}